version: '3'

services:

  web-django-auth:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db-django-auth
  

  db-django-auth:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
 
