version: '3'

services:
  api_auth:
    build:
      context: ./backend/api_auth/api_users
    volumes:
      - ./backend/api_auth/api_users:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/api_auth/api_users/.env
    networks:
      - backend
    depends_on:
      - db-django-auth

  management_service:
    build:
      context: ./backend/management_service
    volumes:
      - ./backend/management_service:/app
    ports:
      - "5000:5000"
    env_file:
      - ./backend/management_service/.env
    networks:
      - backend
    depends_on:
      - db-flask-ms

  notification_service:
    build:
      context: ./backend/notification_service
    volumes:
      - ./backend/notification_service:/app
    ports:
      - "9000:9000"
    env_file:
      - ./backend/notification_service/.env
    networks:
      - backend
    

  frontend:
  build:
    context: ./frontend
  volumes:
    - ./frontend:/app
    - /app/node_modules
  ports:
    - "80:80"
  networks:
    - frontend
  
  db-flask-ms:
    image: postgres
    ports:
      - "5430:5430"
    restart: always
    env_file:
      - ./backend/management_service/.env
    volumes:
      - ./backend/management_service/postgres-data:/var/lib/postgresql/data
    command: ["postgres", "-c", "port=5430"]
    networks:
      - backend
  
  db-django-auth:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./backend/api_auth/api_users/.env
    volumes:
      - ./backend/api_auth/api_users/postgres-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
  frontend:
