# Generated by Django 5.0.6 on 2024-07-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodeluser',
            name='first_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='custommodeluser',
            name='last_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
