# Generated by Django 5.0.6 on 2024-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_custommodeluser_first_name_custommodeluser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommodeluser',
            name='username',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
