# Generated by Django 5.0.6 on 2024-07-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_custommodeluser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodeluser',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='custommodeluser',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='custommodeluser',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='custommodeluser',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
