"""empty message

Revision ID: 2a81bed67f17
Revises: a20d00d28072
Create Date: 2024-07-22 20:49:41.014630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a81bed67f17'
down_revision = 'a20d00d28072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('job', sa.Enum('DEVELOPER', 'DESIGNER', 'MANAGER', name='roleenum'), nullable=False))
        batch_op.drop_column('role')
        batch_op.drop_column('full_name')
        batch_op.drop_column('date_for_interview')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_for_interview', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('role', postgresql.ENUM('DEVELOPER', 'DESIGNER', 'MANAGER', name='roleenum'), autoincrement=False, nullable=False))
        batch_op.drop_column('job')
        batch_op.drop_column('img')
        batch_op.drop_column('date')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
