"""empty message

Revision ID: 858ab929d6bd
Revises: 2a81bed67f17
Create Date: 2024-07-22 21:17:10.607481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '858ab929d6bd'
down_revision = '2a81bed67f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('job',
               existing_type=postgresql.ENUM('DEVELOPER', 'DESIGNER', 'MANAGER', name='roleenum'),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('FIRST', 'SECOND', 'THIRD', name='stageenum'),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('FIRST', 'SECOND', 'THIRD', name='stageenum'),
               existing_nullable=False)
        batch_op.alter_column('job',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DEVELOPER', 'DESIGNER', 'MANAGER', name='roleenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
