"""empty message

Revision ID: a20d00d28072
Revises: 
Create Date: 2024-07-21 20:52:35.520598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20d00d28072'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('date_for_interview', sa.Date(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('DEVELOPER', 'DESIGNER', 'MANAGER', name='roleenum'), nullable=False),
    sa.Column('status', sa.Enum('FIRST', 'SECOND', 'THIRD', name='stageenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidates')
    # ### end Alembic commands ###
